/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import javax.swing.ImageIcon;
   
/**
 *
 * @author aleja
 */
public class Book_Activities extends javax.swing.JFrame { 
     int tipo;
    /**
     * Creates new form Book_Activities
     */
    public Book_Activities() {
        initComponents(); 
        panel_Description.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_bookActivities = new javax.swing.JPanel();
        panel_Description = new javax.swing.JPanel();
        name_tour = new javax.swing.JLabel();
        moneda = new javax.swing.JLabel();
        moneda1 = new javax.swing.JLabel();
        btn_cancelar = new javax.swing.JButton();
        btn_siguiente = new javax.swing.JButton();
        description = new javax.swing.JLabel();
        title_child = new javax.swing.JLabel();
        title_adult = new javax.swing.JLabel();
        child_price = new javax.swing.JLabel();
        adult_price = new javax.swing.JLabel();
        banner = new javax.swing.JLabel();
        img_tour = new javax.swing.JLabel();
        btn_jungle = new javax.swing.JButton();
        btn_mangrove = new javax.swing.JButton();
        btn_scuba = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_bookActivities.setBackground(new java.awt.Color(255, 255, 255));
        panel_bookActivities.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_Description.setBackground(new java.awt.Color(222, 222, 222));
        panel_Description.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name_tour.setFont(new java.awt.Font("Roboto Lt", 0, 48)); // NOI18N
        name_tour.setForeground(new java.awt.Color(255, 255, 255));
        panel_Description.add(name_tour, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 510, 60));

        moneda.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        moneda.setForeground(new java.awt.Color(255, 255, 255));
        moneda.setText("USD");
        panel_Description.add(moneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 227, -1, 10));

        moneda1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        moneda1.setForeground(new java.awt.Color(255, 255, 255));
        moneda1.setText("USD");
        panel_Description.add(moneda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 227, -1, 10));

        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_Cancelar.jpg"))); // NOI18N
        btn_cancelar.setBorderPainted(false);
        btn_cancelar.setContentAreaFilled(false);
        btn_cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        panel_Description.add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 700, 100, 50));

        btn_siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_Siguiente.jpg"))); // NOI18N
        btn_siguiente.setActionCommand("");
        btn_siguiente.setBorderPainted(false);
        btn_siguiente.setContentAreaFilled(false);
        btn_siguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_siguienteActionPerformed(evt);
            }
        });
        panel_Description.add(btn_siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 700, 100, 50));

        description.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        description.setForeground(new java.awt.Color(153, 153, 153));
        panel_Description.add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 500, 500));

        title_child.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        title_child.setForeground(new java.awt.Color(255, 255, 255));
        title_child.setText("Child");
        panel_Description.add(title_child, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        title_adult.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        title_adult.setForeground(new java.awt.Color(255, 255, 255));
        title_adult.setText("Adult");
        panel_Description.add(title_adult, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        child_price.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        child_price.setForeground(new java.awt.Color(255, 255, 255));
        child_price.setText("$00.00");
        panel_Description.add(child_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        adult_price.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        adult_price.setForeground(new java.awt.Color(255, 255, 255));
        adult_price.setText("$00.00");
        panel_Description.add(adult_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        banner.setToolTipText("");
        panel_Description.add(banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 510, 100));
        panel_Description.add(img_tour, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 180));

        panel_bookActivities.add(panel_Description, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 0, -1, 760));

        btn_jungle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/A_Jungle_02.jpg"))); // NOI18N
        btn_jungle.setBorderPainted(false);
        btn_jungle.setContentAreaFilled(false);
        btn_jungle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_jungle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_jungleActionPerformed(evt);
            }
        });
        panel_bookActivities.add(btn_jungle, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 370, -1));

        btn_mangrove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/A_Mangrove_02.jpg"))); // NOI18N
        btn_mangrove.setBorderPainted(false);
        btn_mangrove.setContentAreaFilled(false);
        btn_mangrove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_mangrove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mangroveActionPerformed(evt);
            }
        });
        panel_bookActivities.add(btn_mangrove, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 370, -1));

        btn_scuba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/A_Scuba_03.jpg"))); // NOI18N
        btn_scuba.setBorderPainted(false);
        btn_scuba.setContentAreaFilled(false);
        btn_scuba.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_scuba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_scubaActionPerformed(evt);
            }
        });
        panel_bookActivities.add(btn_scuba, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 370, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/A_Box_ComingSoon.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_bookActivities.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, 370, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/A_Box_ComingSoon.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_bookActivities.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 370, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_bookActivities, javax.swing.GroupLayout.PREFERRED_SIZE, 1300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_bookActivities, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_jungleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_jungleActionPerformed
        // TODO add your handling code here
        tipo = 1;    
        panel_Description.setVisible(true);
        ImageIcon img = new ImageIcon(getClass().getResource("/img/A_Jungle_02.jpg")); 
        ImageIcon ban = new ImageIcon(getClass().getResource("/img/A_BigBar_Green_02.png"));
        img_tour.setIcon(img);  
        banner.setIcon(ban); 
        name_tour.setText("Jungle Tour"); 
        adult_price.setText("$");//BD
        child_price.setText("$"); //BD
        description.setText("<html><p>Get to drive your own speedboat on Cancun’s signature snorkel tour. "
                + "The adventure starts off by steering through the dense mangroves onto Punta Nizuc’s Coral Reef, "
                + "where you will be able to snorkel and discover the astonishing sea life!</p> "
                + "<br><p>What’s included</p><p>-Speedboat ride (Up to two pax per boat – there will be an extra charge for a single rides. Families may ask for a 4 pax boat).</p>"
                + "<p>-Snorkel gear.</p><p>-Bilingual tour guide.</p><p>-Bottled water.</p><p>-Locker</p><br><p>Does not include</p><p>-Dock fee $10 usd.</p><p>-Photos</p><p>-Tips</p></html>"); 
    }//GEN-LAST:event_btn_jungleActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:   
        tipo=0;
        ImageIcon img = new ImageIcon(getClass().getResource("")); 
        ImageIcon ban = new ImageIcon(getClass().getResource(""));
        img_tour.setIcon(img);  
        banner.setIcon(ban); 
        name_tour.setText("");
        adult_price.setText("");//BD
        child_price.setText("");
        description.setText(""); 
        panel_Description.setVisible(false);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_mangroveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mangroveActionPerformed
        // TODO add your handling code here: 
        tipo=2;
        panel_Description.setVisible(true);
        ImageIcon img = new ImageIcon(getClass().getResource("/img/A_Mangrove_02.jpg"));
        ImageIcon ban = new ImageIcon(getClass().getResource("/img/A_BigBar_Green_03.png"));
        img_tour.setIcon(img);  
        banner.setIcon(ban); 
        name_tour.setText("Mangrove  Tour");  
        adult_price.setText("$");//BD
        child_price.setText("$"); //BD
        description.setText("<html><p>Enjoy the thrill of driving your own speedboat while enjoying the sight of mangroves and local wildlife. Stopping for a refreshing swim at “Playa Conchitas”.</p> "
                + "<p>Duration 1.40h</p><br><p>What’s included</p><p>-Speedboat ride (Up to two pax per boat – there will be an extra charge for a single rides. Families may ask for a 4 pax boat).</p>"
                + "<p>-Snorkel gear.</p><p>-Bilingual tour guide.</p><p>-Bottled water.</p><p>-Locker</p><br><p>Does not include</p><p>-Dock [fee $10 usd.]</p><p>-Photos</p><p>-Tips</p></html>"); 
    }//GEN-LAST:event_btn_mangroveActionPerformed

    private void btn_scubaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_scubaActionPerformed
        // TODO add your handling code here: 
        tipo=3;
        panel_Description.setVisible(true); 
        ImageIcon img = new ImageIcon(getClass().getResource("/img/A_Scuba_03.jpg")); 
        ImageIcon ban = new ImageIcon(getClass().getResource("/img/A_BigBar_Blue_01.png"));
        img_tour.setIcon(img);  
        banner.setIcon(ban); 
        name_tour.setText("Scuba Dive"); 
        child_price.setText(""); //BD
        description.setText("<html><p>Enjoy the thrill of driving your own speedboat while enjoying the sight of mangroves and local wildlife. Stopping for a refreshing swim at “Playa Conchitas”.</p> "
                + "<p>Duration 1.40h</p><br><p>What’s included</p><p>-Speedboat ride (Up to two pax per boat – there will be an extra charge for a single rides. Families may ask for a 4 pax boat).</p>"
                + "<p>-Snorkel gear.</p><p>-Bilingual tour guide.</p><p>-Bottled water.</p><p>-Locker</p><br><p>Does not include</p><p>-Dock [fee $10 usd.]</p><p>-Photos</p><p>-Tips</p></html>");
    }//GEN-LAST:event_btn_scubaActionPerformed

    private void btn_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_siguienteActionPerformed
        // TODO add your handling code here: 
        
    }//GEN-LAST:event_btn_siguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Book_Activities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Book_Activities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Book_Activities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Book_Activities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Book_Activities().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adult_price;
    private javax.swing.JLabel banner;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_jungle;
    private javax.swing.JButton btn_mangrove;
    private javax.swing.JButton btn_scuba;
    private javax.swing.JButton btn_siguiente;
    private javax.swing.JLabel child_price;
    private javax.swing.JLabel description;
    private javax.swing.JLabel img_tour;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel moneda;
    private javax.swing.JLabel moneda1;
    private javax.swing.JLabel name_tour;
    private javax.swing.JPanel panel_Description;
    private javax.swing.JPanel panel_bookActivities;
    private javax.swing.JLabel title_adult;
    private javax.swing.JLabel title_child;
    // End of variables declaration//GEN-END:variables
}
