/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

/**
 *
 * @author aleja
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jtext_nombre = new javax.swing.JTextField();
        jtext_confirmar = new javax.swing.JTextField();
        jtext_contrasenaAdmin = new javax.swing.JTextField();
        jtext_contrasena = new javax.swing.JTextField();
        jlabel_unlock = new javax.swing.JLabel();
        jlabel_lock = new javax.swing.JLabel();
        jlabel_key = new javax.swing.JLabel();
        jlabel_close = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jlabel_line = new javax.swing.JLabel();
        jlabel_line1 = new javax.swing.JLabel();
        jlabel_line2 = new javax.swing.JLabel();
        jlabel_line3 = new javax.swing.JLabel();
        jlabel_personplus = new javax.swing.JLabel();
        jlabel_fondo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel2.setLayout(null);

        jtext_nombre.setText("Nombre");
        jtext_nombre.setBorder(null);
        jPanel2.add(jtext_nombre);
        jtext_nombre.setBounds(70, 200, 370, 30);

        jtext_confirmar.setText("Confirmar contrasena");
        jtext_confirmar.setBorder(null);
        jPanel2.add(jtext_confirmar);
        jtext_confirmar.setBounds(70, 320, 370, 30);

        jtext_contrasenaAdmin.setText("Contrasena administrador");
        jtext_contrasenaAdmin.setBorder(null);
        jPanel2.add(jtext_contrasenaAdmin);
        jtext_contrasenaAdmin.setBounds(70, 380, 370, 30);

        jtext_contrasena.setText("Contrasena");
        jtext_contrasena.setBorder(null);
        jPanel2.add(jtext_contrasena);
        jtext_contrasena.setBounds(70, 260, 370, 30);

        jlabel_unlock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SI_Bt_Unlock.png"))); // NOI18N
        jPanel2.add(jlabel_unlock);
        jlabel_unlock.setBounds(460, 250, 24, 30);

        jlabel_lock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SI_Bt_Lock.png"))); // NOI18N
        jPanel2.add(jlabel_lock);
        jlabel_lock.setBounds(460, 310, 20, 30);

        jlabel_key.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SI_Bt_Key.png"))); // NOI18N
        jPanel2.add(jlabel_key);
        jlabel_key.setBounds(450, 380, 24, 30);

        jlabel_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SI_Bt_Cerrar.png"))); // NOI18N
        jPanel2.add(jlabel_close);
        jlabel_close.setBounds(520, 0, 20, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SI_Btn_SignIn.png"))); // NOI18N
        jButton1.setBorder(null);
        jPanel2.add(jButton1);
        jButton1.setBounds(300, 440, 180, 50);

        jlabel_line.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SI_Bt_Line.png"))); // NOI18N
        jPanel2.add(jlabel_line);
        jlabel_line.setBounds(70, 220, 410, 30);

        jlabel_line1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SI_Bt_Line.png"))); // NOI18N
        jPanel2.add(jlabel_line1);
        jlabel_line1.setBounds(70, 400, 410, 30);

        jlabel_line2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SI_Bt_Line.png"))); // NOI18N
        jPanel2.add(jlabel_line2);
        jlabel_line2.setBounds(70, 340, 410, 30);

        jlabel_line3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SI_Bt_Line.png"))); // NOI18N
        jPanel2.add(jlabel_line3);
        jlabel_line3.setBounds(70, 280, 410, 30);

        jlabel_personplus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SI_Bt_PersonPlus.png"))); // NOI18N
        jPanel2.add(jlabel_personplus);
        jlabel_personplus.setBounds(460, 190, 20, 30);

        jlabel_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SI_Box.jpg"))); // NOI18N
        jlabel_fondo.setText("jLabel3");
        jPanel2.add(jlabel_fondo);
        jlabel_fondo.setBounds(0, 0, 540, 510);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(80, 19, 540, 510);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MPE__SignIn_A.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(31, 5, 1107, 528);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlabel_close;
    private javax.swing.JLabel jlabel_fondo;
    private javax.swing.JLabel jlabel_key;
    private javax.swing.JLabel jlabel_line;
    private javax.swing.JLabel jlabel_line1;
    private javax.swing.JLabel jlabel_line2;
    private javax.swing.JLabel jlabel_line3;
    private javax.swing.JLabel jlabel_lock;
    private javax.swing.JLabel jlabel_personplus;
    private javax.swing.JLabel jlabel_unlock;
    private javax.swing.JTextField jtext_confirmar;
    private javax.swing.JTextField jtext_contrasena;
    private javax.swing.JTextField jtext_contrasenaAdmin;
    private javax.swing.JTextField jtext_nombre;
    // End of variables declaration//GEN-END:variables
}
