/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows; 

import javax.swing.*;




/**
 *
 * @author aleja
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */ 
    int x,y;
    public LogIn() {
        initComponents();  
        AWTUtilities.setOpaque(this, false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSign = new javax.swing.JPanel();
        jLabel_dragger = new javax.swing.JLabel();
        jButton_close = new javax.swing.JButton();
        jLabel_signIn = new javax.swing.JLabel();
        jtext_nombre = new javax.swing.JTextField();
        jtext_confirmar = new javax.swing.JTextField();
        jtext_contrasenaAdmin = new javax.swing.JTextField();
        jtext_contrasena = new javax.swing.JTextField();
        jlabel_unlock = new javax.swing.JLabel();
        jlabel_lock = new javax.swing.JLabel();
        jlabel_key = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton_signIn = new javax.swing.JButton();
        jlabel_line = new javax.swing.JLabel();
        jlabel_line1 = new javax.swing.JLabel();
        jlabel_line2 = new javax.swing.JLabel();
        jlabel_line3 = new javax.swing.JLabel();
        jlabel_personplus = new javax.swing.JLabel();
        jRadioButton_admin = new javax.swing.JRadioButton();
        jRadioButton_vendedor = new javax.swing.JRadioButton();
        jlabel_fondo = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        panelChangeLogin = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.white);
        setUndecorated(true);

        panelSign.setLayout(null);

        jLabel_dragger.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel_draggerMouseDragged(evt);
            }
        });
        jLabel_dragger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_draggerMousePressed(evt);
            }
        });
        panelSign.add(jLabel_dragger);
        jLabel_dragger.setBounds(0, 0, 520, 30);

        jButton_close.setBackground(new java.awt.Color(255, 255, 255));
        jButton_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SI_Bt_Cerrar.png"))); // NOI18N
        jButton_close.setBorder(null);
        jButton_close.setBorderPainted(false);
        jButton_close.setContentAreaFilled(false);
        jButton_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_closeMouseExited(evt);
            }
        });
        jButton_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_closeActionPerformed(evt);
            }
        });
        panelSign.add(jButton_close);
        jButton_close.setBounds(510, 0, 30, 30);

        jLabel_signIn.setFont(new java.awt.Font("Roboto", 1, 28)); // NOI18N
        jLabel_signIn.setForeground(new java.awt.Color(0, 123, 164));
        jLabel_signIn.setText("SIGN IN");
        panelSign.add(jLabel_signIn);
        jLabel_signIn.setBounds(60, 80, 110, 40);

        jtext_nombre.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jtext_nombre.setForeground(new java.awt.Color(147, 149, 152));
        jtext_nombre.setText("Nombre");
        jtext_nombre.setBorder(null);
        jtext_nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtext_nombreMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtext_nombreMouseExited(evt);
            }
        });
        panelSign.add(jtext_nombre);
        jtext_nombre.setBounds(70, 190, 370, 30);

        jtext_confirmar.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jtext_confirmar.setForeground(new java.awt.Color(147, 149, 152));
        jtext_confirmar.setText("Confirmar contrasena");
        jtext_confirmar.setBorder(null);
        panelSign.add(jtext_confirmar);
        jtext_confirmar.setBounds(70, 310, 370, 30);

        jtext_contrasenaAdmin.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jtext_contrasenaAdmin.setForeground(new java.awt.Color(147, 149, 152));
        jtext_contrasenaAdmin.setText("Contrasena administrador");
        jtext_contrasenaAdmin.setBorder(null);
        jtext_contrasenaAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext_contrasenaAdminActionPerformed(evt);
            }
        });
        panelSign.add(jtext_contrasenaAdmin);
        jtext_contrasenaAdmin.setBounds(70, 370, 370, 30);

        jtext_contrasena.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jtext_contrasena.setForeground(new java.awt.Color(147, 149, 152));
        jtext_contrasena.setText("Contrasena");
        jtext_contrasena.setBorder(null);
        panelSign.add(jtext_contrasena);
        jtext_contrasena.setBounds(70, 250, 370, 30);

        jlabel_unlock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SI_Bt_Unlock.png"))); // NOI18N
        panelSign.add(jlabel_unlock);
        jlabel_unlock.setBounds(460, 240, 24, 30);

        jlabel_lock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SI_Bt_Lock.png"))); // NOI18N
        panelSign.add(jlabel_lock);
        jlabel_lock.setBounds(460, 300, 20, 30);

        jlabel_key.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SI_Bt_Key.png"))); // NOI18N
        panelSign.add(jlabel_key);
        jlabel_key.setBounds(450, 370, 24, 30);

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(241, 242, 242));
        jLabel2.setText("Sign in");
        panelSign.add(jLabel2);
        jLabel2.setBounds(360, 440, 60, 30);

        jButton_signIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SI_Btn_SignIn.png"))); // NOI18N
        jButton_signIn.setToolTipText("");
        jButton_signIn.setBorder(null);
        jButton_signIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_signInActionPerformed(evt);
            }
        });
        panelSign.add(jButton_signIn);
        jButton_signIn.setBounds(300, 430, 180, 50);

        jlabel_line.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SI_Bt_Line.png"))); // NOI18N
        panelSign.add(jlabel_line);
        jlabel_line.setBounds(70, 210, 410, 30);

        jlabel_line1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SI_Bt_Line.png"))); // NOI18N
        panelSign.add(jlabel_line1);
        jlabel_line1.setBounds(70, 390, 410, 30);

        jlabel_line2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SI_Bt_Line.png"))); // NOI18N
        panelSign.add(jlabel_line2);
        jlabel_line2.setBounds(70, 330, 410, 30);

        jlabel_line3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SI_Bt_Line.png"))); // NOI18N
        panelSign.add(jlabel_line3);
        jlabel_line3.setBounds(70, 270, 410, 30);

        jlabel_personplus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SI_Bt_PersonPlus.png"))); // NOI18N
        panelSign.add(jlabel_personplus);
        jlabel_personplus.setBounds(460, 180, 20, 30);

        jRadioButton_admin.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton_admin.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jRadioButton_admin.setForeground(new java.awt.Color(147, 149, 152));
        jRadioButton_admin.setText("Administrador");
        panelSign.add(jRadioButton_admin);
        jRadioButton_admin.setBounds(60, 440, 100, 23);

        jRadioButton_vendedor.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton_vendedor.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jRadioButton_vendedor.setForeground(new java.awt.Color(147, 149, 152));
        jRadioButton_vendedor.setText("Vendedor");
        panelSign.add(jRadioButton_vendedor);
        jRadioButton_vendedor.setBounds(170, 440, 80, 23);

        jlabel_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SI_Box.jpg"))); // NOI18N
        jlabel_fondo.setText("jLabel3");
        panelSign.add(jlabel_fondo);
        jlabel_fondo.setBounds(0, 0, 540, 500);

        jPasswordField1.setText("jPasswordField1");
        panelSign.add(jPasswordField1);
        jPasswordField1.setBounds(180, 150, 111, 20);

        jPanel4.setLayout(null);

        panelChangeLogin.setBackground(new java.awt.Color(0, 169, 207));
        panelChangeLogin.setOpaque(false);
        panelChangeLogin.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(241, 242, 242));
        jLabel6.setText("experencias.");
        panelChangeLogin.add(jLabel6);
        jLabel6.setBounds(20, 100, 320, 40);

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(241, 242, 242));
        jLabel4.setText("En Marina Punta del Este Proveemos las mejores ");
        panelChangeLogin.add(jLabel4);
        jLabel4.setBounds(20, 80, 320, 40);

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(241, 242, 242));
        jLabel5.setText("¿Tienes ya una cuenta?");
        panelChangeLogin.add(jLabel5);
        jLabel5.setBounds(20, 50, 210, 40);

        jButton3.setBackground(new java.awt.Color(255, 0, 102));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SI_Bt_LogIn_02.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        panelChangeLogin.add(jButton3);
        jButton3.setBounds(20, 130, 190, 60);

        jPanel4.add(panelChangeLogin);
        panelChangeLogin.setBounds(620, 100, 330, 190);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SI_Background.png"))); // NOI18N
        background.setText("jLabel4");
        jPanel4.add(background);
        background.setBounds(0, 0, 1001, 420);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(panelSign, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(402, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(21, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(22, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(panelSign, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(64, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(74, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_signInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_signInActionPerformed
     
    }//GEN-LAST:event_jButton_signInActionPerformed

    private void jButton_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_closeActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButton_closeActionPerformed

    private void jLabel_draggerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_draggerMouseDragged
        // TODO add your handling code here: 
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_jLabel_draggerMouseDragged

    private void jLabel_draggerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_draggerMousePressed
        // TODO add your handling code here: 
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabel_draggerMousePressed

    private void jtext_contrasenaAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext_contrasenaAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext_contrasenaAdminActionPerformed

    private void jtext_nombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtext_nombreMouseClicked
        // TODO add your handling code here: 
        jtext_nombre.setText(""); 
        
    }//GEN-LAST:event_jtext_nombreMouseClicked

    private void jtext_nombreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtext_nombreMouseExited
        // TODO add your handling code here: 
        
    }//GEN-LAST:event_jtext_nombreMouseExited

    private void jButton_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_closeMouseEntered
        // TODO add your handling code here:  

        ImageIcon img;
        img = new ImageIcon ("\\img\\SI_bt_Cerrar_Selec.png");
        jButton_close.setIcon(img); 
    }//GEN-LAST:event_jButton_closeMouseEntered

    private void jButton_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_closeMouseExited
        // TODO add your handling code here: 
        ImageIcon img;
        img = new ImageIcon ("\\img\\SI_bt_Cerrar.png");
        jButton_close.setIcon(img);
    }//GEN-LAST:event_jButton_closeMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold> 
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true); 
                
            }
        }); 
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton_close;
    private javax.swing.JButton jButton_signIn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_dragger;
    private javax.swing.JLabel jLabel_signIn;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton_admin;
    private javax.swing.JRadioButton jRadioButton_vendedor;
    private javax.swing.JLabel jlabel_fondo;
    private javax.swing.JLabel jlabel_key;
    private javax.swing.JLabel jlabel_line;
    private javax.swing.JLabel jlabel_line1;
    private javax.swing.JLabel jlabel_line2;
    private javax.swing.JLabel jlabel_line3;
    private javax.swing.JLabel jlabel_lock;
    private javax.swing.JLabel jlabel_personplus;
    private javax.swing.JLabel jlabel_unlock;
    private javax.swing.JTextField jtext_confirmar;
    private javax.swing.JTextField jtext_contrasena;
    private javax.swing.JTextField jtext_contrasenaAdmin;
    private javax.swing.JTextField jtext_nombre;
    private javax.swing.JPanel panelChangeLogin;
    private javax.swing.JPanel panelSign;
    // End of variables declaration//GEN-END:variables
}
