/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

/**
 *
 * @author aleja
 */
public class Ventas extends javax.swing.JFrame {

    /**
     * Creates new form Ventas
     */
    public Ventas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_drag = new javax.swing.JPanel();
        btn_cerrar = new javax.swing.JLabel();
        btn_minimizar = new javax.swing.JLabel();
        drag = new javax.swing.JLabel();
        panel_pasos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fondo_pasos = new javax.swing.JLabel();
        panel_opciones = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        guy = new javax.swing.JLabel();
        icon_guy = new javax.swing.JLabel();
        box = new javax.swing.JLabel();
        panel_general = new javax.swing.JPanel();
        input_infante = new javax.swing.JTextField();
        input_nino = new javax.swing.JTextField();
        input_adulto = new javax.swing.JTextField();
        moneda = new javax.swing.JLabel();
        precioFinal = new javax.swing.JLabel();
        fondito6 = new javax.swing.JLabel();
        fondito5 = new javax.swing.JLabel();
        fondito4 = new javax.swing.JLabel();
        fondito3 = new javax.swing.JLabel();
        fondito2 = new javax.swing.JLabel();
        fondito1 = new javax.swing.JLabel();
        btn_usa = new javax.swing.JLabel();
        btn_mxn = new javax.swing.JLabel();
        btn_codigoPromocion = new javax.swing.JLabel();
        btn_seguirComprando = new javax.swing.JLabel();
        btn_cancelar = new javax.swing.JLabel();
        btn_siguiente = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panel_calendario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1600, 900));
        setMinimumSize(new java.awt.Dimension(1600, 900));
        setPreferredSize(new java.awt.Dimension(1600, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_drag.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Btn_Cerrar_1_Normal.png"))); // NOI18N
        panel_drag.add(btn_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1540, 0, -1, -1));

        btn_minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Btn_Recurso 100_Normal.png"))); // NOI18N
        panel_drag.add(btn_minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 0, 40, -1));

        drag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/TB_Bar.jpg"))); // NOI18N
        drag.setPreferredSize(new java.awt.Dimension(1600, 42));
        panel_drag.add(drag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        getContentPane().add(panel_drag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 40));

        panel_pasos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BC_Icn_Divider.png"))); // NOI18N
        panel_pasos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 10, 20, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BC_Icn_Car.png"))); // NOI18N
        panel_pasos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 10, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BC_Icn_Conection.png"))); // NOI18N
        panel_pasos.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, -1, 30));

        fondo_pasos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BC_Main_TopBar.png"))); // NOI18N
        fondo_pasos.setMaximumSize(new java.awt.Dimension(1300, 80));
        fondo_pasos.setMinimumSize(new java.awt.Dimension(1300, 80));
        fondo_pasos.setPreferredSize(new java.awt.Dimension(1300, 80));
        panel_pasos.add(fondo_pasos, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 1320, 90));

        getContentPane().add(panel_pasos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 1300, 80));

        panel_opciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre de Usuario");
        panel_opciones.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        guy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BC_Icn_Contact_02.png"))); // NOI18N
        panel_opciones.add(guy, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, 60));

        icon_guy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BC_Icn_ContactBubble.png"))); // NOI18N
        panel_opciones.add(icon_guy, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        box.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BC_Box_Left_Extended.png"))); // NOI18N
        box.setMaximumSize(new java.awt.Dimension(300, 830));
        box.setMinimumSize(new java.awt.Dimension(300, 830));
        box.setPreferredSize(new java.awt.Dimension(300, 830));
        panel_opciones.add(box, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 300, 870));

        getContentPane().add(panel_opciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 830));

        panel_general.setBackground(new java.awt.Color(255, 255, 255));
        panel_general.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        input_infante.setFont(new java.awt.Font("Roboto", 0, 55)); // NOI18N
        input_infante.setText("0");
        input_infante.setAutoscrolls(false);
        input_infante.setBorder(null);
        input_infante.setOpaque(false);
        panel_general.add(input_infante, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 330, 60, 60));

        input_nino.setFont(new java.awt.Font("Roboto", 0, 55)); // NOI18N
        input_nino.setText("0");
        input_nino.setAutoscrolls(false);
        input_nino.setBorder(null);
        input_nino.setOpaque(false);
        panel_general.add(input_nino, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 230, 60, 60));

        input_adulto.setFont(new java.awt.Font("Roboto", 0, 55)); // NOI18N
        input_adulto.setText("0");
        input_adulto.setAutoscrolls(false);
        input_adulto.setBorder(null);
        input_adulto.setOpaque(false);
        panel_general.add(input_adulto, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 130, 60, 60));

        moneda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ag_btn_mx.png"))); // NOI18N
        moneda.setToolTipText("");
        panel_general.add(moneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 570, -1, -1));

        precioFinal.setFont(new java.awt.Font("Roboto", 0, 62)); // NOI18N
        precioFinal.setText("$000.00");
        panel_general.add(precioFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 530, -1, -1));

        fondito6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ag_Btn_Price.jpg"))); // NOI18N
        panel_general.add(fondito6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 320, -1, -1));

        fondito5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ag_Btn_Price.jpg"))); // NOI18N
        panel_general.add(fondito5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 220, -1, -1));

        fondito4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ag_Btn_Price.jpg"))); // NOI18N
        panel_general.add(fondito4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 120, -1, -1));

        fondito3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ag_Btn_Description.jpg"))); // NOI18N
        panel_general.add(fondito3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 320, -1, -1));

        fondito2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ag_Btn_Description.jpg"))); // NOI18N
        panel_general.add(fondito2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 220, -1, -1));

        fondito1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ag_Btn_Description.jpg"))); // NOI18N
        fondito1.setOpaque(true);
        panel_general.add(fondito1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 120, -1, -1));

        btn_usa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ag_btn_usd.png"))); // NOI18N
        panel_general.add(btn_usa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 70, -1, 30));

        btn_mxn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ag_btn_mx_select.png"))); // NOI18N
        panel_general.add(btn_mxn, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 70, -1, -1));

        btn_codigoPromocion.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_codigoPromocion.setForeground(new java.awt.Color(51, 153, 255));
        btn_codigoPromocion.setText("Codigo de promocion");
        panel_general.add(btn_codigoPromocion, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 600, -1, -1));

        btn_seguirComprando.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_Comprar.jpg"))); // NOI18N
        panel_general.add(btn_seguirComprando, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 670, -1, -1));

        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_Cancelar.jpg"))); // NOI18N
        panel_general.add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 670, -1, -1));

        btn_siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_Siguiente.jpg"))); // NOI18N
        panel_general.add(btn_siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 670, -1, -1));

        jLabel18.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel18.setText("Infante");
        panel_general.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 320, -1, -1));

        jLabel17.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel17.setText("Nino");
        panel_general.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 220, -1, -1));

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel16.setText("Adulto");
        panel_general.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 120, -1, -1));

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel15.setText("x");
        panel_general.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 360, 20, 20));

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel14.setText("x");
        panel_general.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 260, 20, 20));

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel13.setText("x");
        panel_general.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 150, 20, 20));

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 123, 164));
        jLabel12.setText("Total");
        panel_general.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 470, -1, -1));

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 123, 164));
        jLabel11.setText("Hora");
        panel_general.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 510, -1, -1));

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 123, 164));
        jLabel10.setText("Precio");
        panel_general.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 123, 164));
        jLabel9.setText("Dia");
        panel_general.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ag_Box_Day.jpg"))); // NOI18N
        panel_general.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 700, 520));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ag_Box_Price.jpg"))); // NOI18N
        panel_general.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ag_Box_Hour.jpg"))); // NOI18N
        panel_general.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, -1, -1));

        getContentPane().add(panel_general, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 1300, 760));

        panel_calendario.setBackground(new java.awt.Color(255, 255, 255));
        panel_calendario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panel_calendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 1300, 760));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/App_BaseComponents.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel box;
    private javax.swing.JLabel btn_cancelar;
    private javax.swing.JLabel btn_cerrar;
    private javax.swing.JLabel btn_codigoPromocion;
    private javax.swing.JLabel btn_minimizar;
    private javax.swing.JLabel btn_mxn;
    private javax.swing.JLabel btn_seguirComprando;
    private javax.swing.JLabel btn_siguiente;
    private javax.swing.JLabel btn_usa;
    private javax.swing.JLabel drag;
    private javax.swing.JLabel fondito1;
    private javax.swing.JLabel fondito2;
    private javax.swing.JLabel fondito3;
    private javax.swing.JLabel fondito4;
    private javax.swing.JLabel fondito5;
    private javax.swing.JLabel fondito6;
    private javax.swing.JLabel fondo_pasos;
    private javax.swing.JLabel guy;
    private javax.swing.JLabel icon_guy;
    private javax.swing.JTextField input_adulto;
    private javax.swing.JTextField input_infante;
    private javax.swing.JTextField input_nino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel moneda;
    private javax.swing.JPanel panel_calendario;
    private javax.swing.JPanel panel_drag;
    private javax.swing.JPanel panel_general;
    private javax.swing.JPanel panel_opciones;
    private javax.swing.JPanel panel_pasos;
    private javax.swing.JLabel precioFinal;
    // End of variables declaration//GEN-END:variables
}
